import { PERMISSIONS } from './permissions';

export const MODULE_ACCESS_PERMISSIONS = {
  cuentas: [
    PERMISSIONS.CUENTAS_CLIENTES_VER,
    PERMISSIONS.CUENTAS_FACTURAS_VER,
    PERMISSIONS.CUENTAS_PAGOS_VER,
    PERMISSIONS.CUENTAS_ABONOS_VER,
    PERMISSIONS.CUENTAS_REPORTES_GENERAR,
  ],
  configuracion: [
    PERMISSIONS.CLIENTES_VER,
    PERMISSIONS.INVENTARIO_UBICACIONES_VER,
    PERMISSIONS.INVENTARIO_UBICACIONES_CREAR,
    PERMISSIONS.INVENTARIO_UBICACIONES_EDITAR,
  ],
  inventario: [
    PERMISSIONS.INVENTARIO_ARTICULOS_VER,
    PERMISSIONS.INVENTARIO_UBICACIONES_VER,
    PERMISSIONS.INVENTARIO_MOVIMIENTOS_VER,
    PERMISSIONS.INVENTARIO_BAJAS_VER,
  ],
  personal: [PERMISSIONS.PERSONAL_VER],
  usuarios: [PERMISSIONS.USUARIOS_VER],
};
