export const PERMISSIONS = {
  CLIENTES_VER: 'clientes.ver',
  CLIENTES_CREAR: 'clientes.crear',
  CLIENTES_EDITAR: 'clientes.editar',
  CLIENTES_ELIMINAR: 'clientes.eliminar',

  CUENTAS_CLIENTES_VER: 'cuentas.clientes.ver',
  CUENTAS_CLIENTES_CREAR: 'cuentas.clientes.crear',
  CUENTAS_CLIENTES_EDITAR: 'cuentas.clientes.editar',
  CUENTAS_CLIENTES_ELIMINAR: 'cuentas.clientes.eliminar',
  CUENTAS_FACTURAS_VER: 'cuentas.facturas.ver',
  CUENTAS_FACTURAS_CREAR: 'cuentas.facturas.crear',
  CUENTAS_FACTURAS_EDITAR: 'cuentas.facturas.editar',
  CUENTAS_FACTURAS_CANCELAR: 'cuentas.facturas.cancelar',
  CUENTAS_FACTURAS_ELIMINAR: 'cuentas.facturas.eliminar',
  CUENTAS_PAGOS_VER: 'cuentas.pagos.ver',
  CUENTAS_PAGOS_CREAR: 'cuentas.pagos.crear',
  CUENTAS_PAGOS_ANULAR: 'cuentas.pagos.anular',
  CUENTAS_PAGOS_ELIMINAR: 'cuentas.pagos.eliminar',
  CUENTAS_ABONOS_VER: 'cuentas.abonos.ver',
  CUENTAS_ABONOS_CREAR: 'cuentas.abonos.crear',
  CUENTAS_ABONOS_ELIMINAR: 'cuentas.abonos.eliminar',
  CUENTAS_REPORTES_GENERAR: 'cuentas.reportes.generar',
  CUENTAS_REPORTES_EXPORTAR: 'cuentas.reportes.exportar',

  INVENTARIO_ARTICULOS_VER: 'inventario.articulos.ver',
  INVENTARIO_ARTICULOS_CREAR: 'inventario.articulos.crear',
  INVENTARIO_ARTICULOS_EDITAR: 'inventario.articulos.editar',
  INVENTARIO_ARTICULOS_ELIMINAR: 'inventario.articulos.eliminar',
  INVENTARIO_ARTICULOS_DAR_BAJA: 'inventario.articulos.dar_baja',
  INVENTARIO_UBICACIONES_VER: 'inventario.ubicaciones.ver',
  INVENTARIO_UBICACIONES_CREAR: 'inventario.ubicaciones.crear',
  INVENTARIO_UBICACIONES_EDITAR: 'inventario.ubicaciones.editar',
  INVENTARIO_UBICACIONES_ELIMINAR: 'inventario.ubicaciones.eliminar',
  INVENTARIO_UBICACIONES_REASIGNAR_CLIENTE: 'inventario.ubicaciones.reasignar_cliente',
  INVENTARIO_MOVIMIENTOS_VER: 'inventario.movimientos.ver',
  INVENTARIO_MOVIMIENTOS_CREAR: 'inventario.movimientos.crear',
  INVENTARIO_MOVIMIENTOS_ANULAR: 'inventario.movimientos.anular',
  INVENTARIO_MOVIMIENTOS_ELIMINAR: 'inventario.movimientos.eliminar',
  INVENTARIO_MOVIMIENTOS_REGENERAR_PDF: 'inventario.movimientos.regenerar_pdf',
  INVENTARIO_BAJAS_VER: 'inventario.bajas.ver',
  INVENTARIO_BAJAS_CREAR: 'inventario.bajas.crear',
  INVENTARIO_BAJAS_ANULAR: 'inventario.bajas.anular',
  INVENTARIO_BAJAS_ELIMINAR: 'inventario.bajas.eliminar',
  INVENTARIO_REPORTES_GENERAR: 'inventario.reportes.generar',
  INVENTARIO_REPORTES_EXPORTAR: 'inventario.reportes.exportar',

  PERSONAL_VER: 'personal.ver',
  PERSONAL_CREAR: 'personal.crear',
  PERSONAL_EDITAR: 'personal.editar',
  PERSONAL_ELIMINAR: 'personal.eliminar',
  PERSONAL_REPORTES_GENERAR: 'personal.reportes.generar',
  PERSONAL_REPORTES_EXPORTAR: 'personal.reportes.exportar',

  USUARIOS_VER: 'usuarios.ver',
  USUARIOS_CREAR: 'usuarios.crear',
  USUARIOS_EDITAR: 'usuarios.editar',
  USUARIOS_ELIMINAR: 'usuarios.eliminar',

  BITACORAS_REGISTRO_CREAR: 'bitacoras.registro.crear',
  BITACORAS_HISTORIAL_VER: 'bitacoras.historial.ver',
  BITACORAS_PUNTOS_VER_TODOS: 'bitacoras.puntos.ver_todos',
  BITACORAS_FORMULARIOS_ADMINISTRAR: 'bitacoras.formularios.administrar',
  BITACORAS_FORMULARIOS_GESTIONAR: 'bitacoras.formularios.gestionar',
  BITACORAS_ASIGNACIONES_ADMINISTRAR: 'bitacoras.asignaciones.administrar',
  BITACORAS_URBANIZACION_ADMINISTRAR: 'bitacoras.urbanizacion.administrar',
};

export const KNOWN_PERMISSIONS = new Set(Object.values(PERMISSIONS));
