import { can, canAny } from '../../../auth/authorization';
import { PERMISSIONS } from '../../../auth/permissions';

export const INVENTORY_ACTIONS = {
  ARTICULOS_VIEW: 'articulos.view',
  ARTICULOS_CREATE: 'articulos.create',
  ARTICULOS_EDIT: 'articulos.edit',
  ARTICULOS_BAJA: 'articulos.baja',
  ARTICULOS_DELETE_ADMIN: 'articulos.deleteAdmin',
  MOVIMIENTOS_VIEW: 'movimientos.view',
  MOVIMIENTOS_CREATE: 'movimientos.create',
  MOVIMIENTOS_VOID: 'movimientos.void',
  MOVIMIENTOS_DELETE_ADMIN: 'movimientos.deleteAdmin',
  MOVIMIENTOS_PDF_DOWNLOAD: 'movimientos.pdf.download',
  MOVIMIENTOS_PDF_REGENERATE: 'movimientos.pdf.regenerate',
  BAJAS_VIEW: 'bajas.view',
  BAJAS_CREATE: 'bajas.create',
  BAJAS_VOID: 'bajas.void',
  BAJAS_DELETE_ADMIN: 'bajas.deleteAdmin',
  REPORTS_EXPORT: 'reports.export',
  LOCATIONS_CREATE_FROM_ARTICLE: 'locations.createFromArticle',
  LOCATIONS_CREATE_FROM_MOVEMENT: 'locations.createFromMovement',
};

export const INVENTORY_RAW_PERMISSIONS = {
  ARTICULOS_VIEW: PERMISSIONS.INVENTARIO_ARTICULOS_VER,
  ARTICULOS_CREATE: PERMISSIONS.INVENTARIO_ARTICULOS_CREAR,
  ARTICULOS_EDIT: PERMISSIONS.INVENTARIO_ARTICULOS_EDITAR,
  ARTICULOS_BAJA: PERMISSIONS.INVENTARIO_ARTICULOS_DAR_BAJA,
  ARTICULOS_DELETE_ADMIN: PERMISSIONS.INVENTARIO_ARTICULOS_ELIMINAR,
  UBICACIONES_CREATE: PERMISSIONS.INVENTARIO_UBICACIONES_CREAR,
  MOVIMIENTOS_VIEW: PERMISSIONS.INVENTARIO_MOVIMIENTOS_VER,
  MOVIMIENTOS_CREATE: PERMISSIONS.INVENTARIO_MOVIMIENTOS_CREAR,
  MOVIMIENTOS_VOID: PERMISSIONS.INVENTARIO_MOVIMIENTOS_ANULAR,
  MOVIMIENTOS_DELETE_ADMIN: PERMISSIONS.INVENTARIO_MOVIMIENTOS_ELIMINAR,
  MOVIMIENTOS_PDF_REGENERATE: PERMISSIONS.INVENTARIO_MOVIMIENTOS_REGENERAR_PDF,
  BAJAS_VIEW: PERMISSIONS.INVENTARIO_BAJAS_VER,
  BAJAS_CREATE: PERMISSIONS.INVENTARIO_BAJAS_CREAR,
  BAJAS_VOID: PERMISSIONS.INVENTARIO_BAJAS_ANULAR,
  BAJAS_DELETE_ADMIN: PERMISSIONS.INVENTARIO_BAJAS_ELIMINAR,
  REPORTS_EXPORT: PERMISSIONS.INVENTARIO_REPORTES_EXPORTAR,
};

const ACTION_PERMISSION_MAP = {
  [INVENTORY_ACTIONS.ARTICULOS_VIEW]: PERMISSIONS.INVENTARIO_ARTICULOS_VER,
  [INVENTORY_ACTIONS.ARTICULOS_CREATE]: PERMISSIONS.INVENTARIO_ARTICULOS_CREAR,
  [INVENTORY_ACTIONS.ARTICULOS_EDIT]: PERMISSIONS.INVENTARIO_ARTICULOS_EDITAR,
  [INVENTORY_ACTIONS.ARTICULOS_BAJA]: PERMISSIONS.INVENTARIO_ARTICULOS_DAR_BAJA,
  [INVENTORY_ACTIONS.ARTICULOS_DELETE_ADMIN]: PERMISSIONS.INVENTARIO_ARTICULOS_ELIMINAR,
  [INVENTORY_ACTIONS.MOVIMIENTOS_VIEW]: PERMISSIONS.INVENTARIO_MOVIMIENTOS_VER,
  [INVENTORY_ACTIONS.MOVIMIENTOS_CREATE]: PERMISSIONS.INVENTARIO_MOVIMIENTOS_CREAR,
  [INVENTORY_ACTIONS.MOVIMIENTOS_VOID]: PERMISSIONS.INVENTARIO_MOVIMIENTOS_ANULAR,
  [INVENTORY_ACTIONS.MOVIMIENTOS_DELETE_ADMIN]: PERMISSIONS.INVENTARIO_MOVIMIENTOS_ELIMINAR,
  [INVENTORY_ACTIONS.MOVIMIENTOS_PDF_DOWNLOAD]: PERMISSIONS.INVENTARIO_MOVIMIENTOS_VER,
  [INVENTORY_ACTIONS.MOVIMIENTOS_PDF_REGENERATE]: PERMISSIONS.INVENTARIO_MOVIMIENTOS_REGENERAR_PDF,
  [INVENTORY_ACTIONS.BAJAS_VIEW]: PERMISSIONS.INVENTARIO_BAJAS_VER,
  [INVENTORY_ACTIONS.BAJAS_CREATE]: [
    PERMISSIONS.INVENTARIO_BAJAS_CREAR,
    PERMISSIONS.INVENTARIO_ARTICULOS_DAR_BAJA,
  ],
  [INVENTORY_ACTIONS.BAJAS_VOID]: PERMISSIONS.INVENTARIO_BAJAS_ANULAR,
  [INVENTORY_ACTIONS.BAJAS_DELETE_ADMIN]: PERMISSIONS.INVENTARIO_BAJAS_ELIMINAR,
  [INVENTORY_ACTIONS.REPORTS_EXPORT]: PERMISSIONS.INVENTARIO_REPORTES_EXPORTAR,
};

const canInventoryAction = (user, action) => {
  if (action === INVENTORY_ACTIONS.LOCATIONS_CREATE_FROM_ARTICLE) {
    return canAny(user, [
      PERMISSIONS.INVENTARIO_UBICACIONES_CREAR,
      PERMISSIONS.INVENTARIO_ARTICULOS_CREAR,
    ]);
  }
  if (action === INVENTORY_ACTIONS.LOCATIONS_CREATE_FROM_MOVEMENT) {
    return can(user, PERMISSIONS.INVENTARIO_UBICACIONES_CREAR);
  }
  return canAny(user, ACTION_PERMISSION_MAP[action]);
};

export const getInventoryPermissions = (user) => {
  const role = user?.tipo_usuario;
  const hasInventoryAccessAction = Object.values(ACTION_PERMISSION_MAP).some((permission) =>
    canAny(user, permission)
  );
  return {
    role,
    canAccessInventory: hasInventoryAccessAction,
    can: (action) => canInventoryAction(user, action),
  };
};

export const hasInventoryAction = (user, action) => getInventoryPermissions(user).can(action);

export const canCreateLocationFromArticle = (user) =>
  getInventoryPermissions(user).can(INVENTORY_ACTIONS.LOCATIONS_CREATE_FROM_ARTICLE);

export const canCreateLocationFromMovement = (user) => {
  const permissions = getInventoryPermissions(user);
  return permissions.can(INVENTORY_ACTIONS.LOCATIONS_CREATE_FROM_MOVEMENT);
};
